name: 'Trigger Workflow and Wait'
description: 'This action triggers a workflow in another repository and waits for the result.'
author: 'Convictional'
branding:
  icon: 'arrow-right'
  color: 'yellow'
inputs:
  owner:
    description: "The owner of the repository where the workflow is contained."
    required: true
  repo:
    description: "The repository where the workflow is contained."
    required: true
  github_token:
    description: "The Github access token with access to the repository. It is recommended you put this token under secrets."
    required: true
  github_user:
    description: "The name of the github user whose access token is being used to trigger the workflow."
    required: false
  ref:
    description: 'The reference of the workflow run. The reference can be a branch, tag, or a commit SHA. Default: main'
    required: false
  wait_interval:
    description: "The number of seconds delay between checking for result of run."
    required: false
  workflow_file_name:
    description: "The reference point. For example, you could use main.yml."
    required: true
  client_payload:
    description: 'Payload to pass to the workflow, must be a JSON string'
    required: false
  propagate_failure:
    description: 'Fail current job if downstream job fails. default: true'
    required: false
  trigger_workflow:
    description: 'Trigger the specified workflow. default: true'
    required: false
  wait_workflow:
    description: 'Wait for workflow to finish. default: true'
    required: false
  comment_downstream_url:
    description: 'Comment API link for commenting the downstream job URL'
    required: false
    default: ''
  comment_github_token:
    description: "The Github access token with access to the repository for comment URL. It is recommended you put this token under secrets."
    required: false
    default: ${{ github.token }}
outputs:
  workflow_id:
    description: The ID of the workflow that was triggered by this action
  workflow_url:
    description: The URL of the workflow that was triggered by this action
  conclusion:
    description: Conclusion of the job, i.e pass/failure
  workflow_run_id:
    description: The ID of the triggered workflow run triggered by this action
  full_sha:
    description: The full SHA of commit that triggered the workflow
  short_sha:
    description: The short SHA of commit that triggered the workflow first 10 chars
runs:
  using: 'docker'
  image: 'Dockerfile'
